### ISSUE TITLE
Tip: .gitignore

### ISSUE THREAD

**Issue by danroxha** [JulioEvencio/rpg_randomico#2]
Iai @JulioEvencio 😁, tudo bem? 
Uma dica caso aceite; vc pode usar o arquivo oculto chamado .gitignore(acho q ñ fica oculta no Windows) nesse arquivo vc pode coloca os arquivo que o git não precisa rastrear.
  
###  Exemplo: 
* Binarios (o programs compilado)
* Arquivos que so servem pra te auxiliar e não tem dependencia com o seu projeto

Caso crie o . gitignore, ele deve conter esse mesmo nome e com o ponto na frente alem de não colocar extensao(.txt, .c, .h, etc)

Aki um video: https://youtu.be/9rElHOJT-qY

**Comment by JulioEvencio** [comment]
> Iai @JulioEvencio , tudo bem?
> Uma dica caso aceite; vc pode usar o arquivo oculto chamado .gitignore(acho q ñ fica oculta no Windows) nesse arquivo vc pode coloca os arquivo que o git não precisa rastrear.
> 
> ### Exemplo:
> * Binarios (o programs compilado)
> * Arquivos que so servem pra te auxiliar e não tem dependencia com o seu projeto
> 
> Caso crie o . gitignore, ele deve conter esse mesmo nome e com o ponto na frente alem de não colocar extensao(.txt, .c, .h, etc)
> 
> Aki um video: https://youtu.be/9rElHOJT-qY

Obrigado pela dica! Acabei de ver o video, vou tentar fazer uns testes aqui, mas ainda não vejo como colocar isso em prática no meu projeto.

**Comment by danroxha** [comment]
> > Iai @JulioEvencio , tudo bem?
> > Uma dica caso aceite; vc pode usar o arquivo oculto chamado .gitignore(acho q ñ fica oculta no Windows) nesse arquivo vc pode coloca os arquivo que o git não precisa rastrear.
> > ### Exemplo:
> > 
> > * Binarios (o programs compilado)
> > * Arquivos que so servem pra te auxiliar e não tem dependencia com o seu projeto
> > 
> > Caso crie o . gitignore, ele deve conter esse mesmo nome e com o ponto na frente alem de não colocar extensao(.txt, .c, .h, etc)
> > Aki um video: https://youtu.be/9rElHOJT-qY
> 
> Obrigado pela dica! Acabei de ver o video, vou tentar fazer uns testes aqui, mas ainda não vejo como colocar isso em prática no meu projeto.

Em relação em como usar no projeto, eh só adicionar o programa executavel pra ser ignorado, já ele não eh necessário no repositorio, isso ja pode ser um ponto de inicio.

OBS: todo respositorio que vc criar, vc pode adicionar o .gitignore msm se vc não for usar
